sudo: required
services:
  - docker

before_install:
  - docker build -t arup/dockertest-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arup/dockertest-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: ""
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
